name: AntiGravity Cron Job

on:
  schedule:
    - cron: '45 2 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: Pythonni sozlash
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Tezroq ishlashi uchun keshdan foydalanamiz

      - name: Kutubxonalarni o'rnatish
        run: |
          pip install -r requirements.txt
          # Faqat kerakli brauzerni o'rnatamiz, tizim paketlariga tegmaymiz
          python -m playwright install chromium --with-deps

      - name: Botni ishga tushirish
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python main_cron.py
