name: AntiGravity Cron Job

on:
  workflow_dispatch: # Endi faqat tugma orqali ishlaydi

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: Pythonni sozlash
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Kutubxonalarni o'rnatish
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium --with-deps

      - name: Botni ishga tushirish
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python main_cron.py







